#!/usr/bin/env python
import rospy

def main():
    rospy.init_node('log_example', log_level=rospy.DEBUG)
    counter = 0
    rate = rospy.Rate(1)
    while not rospy.is_shutdown():
        rospy.logdebug("This is logdebug: %d", counter)
        rospy.loginfo("This is loginfo: %d", counter)
        rospy.logwarn("This is logwarn: %d", counter)
        rospy.logerr("This is logerr: %s", counter)
        rospy.logfatal("This is logfatal: %d", counter)
        counter += 1
        rate.sleep()

if __name__ == '__main__':
    main()