#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Joy
from std_msgs.msg import Float64

class IMRTTeleop:

    def __init__(self):
        self._joint_1_pub = rospy.Publisher('joint_1_position_controller/command', Float64, queue_size=1)
        self._joint_2_pub = rospy.Publisher('joint_2_position_controller/command', Float64, queue_size=1)
        self._joint_3_pub = rospy.Publisher('joint_3_position_controller/command', Float64, queue_size=1)
        rospy.Subscriber('joy', Joy, self._joy_callback)
        self._joint_1_max = 3.1415
        self._joint_2_max = 2.0
        self._joint_3_max = 2.0

    def _joy_callback(self, joy_msg):
    
        self._joint_1_pub.publish(joy_msg.axes[1] * self._joint_1_max)
        self._joint_2_pub.publish(joy_msg.axes[2] * self._joint_2_max)
        self._joint_3_pub.publish(joy_msg.axes[3] * self._joint_3_max)


if __name__ == '__main__':
    rospy.init_node('imrt_teleop')
    IMRTTeleop()
    rospy.loginfo('Node started')
    rospy.spin()
