arm_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1
  pid: {p: 20.0, i: 10.0, d: 6.0}

joint_2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2
  pid: {p: 20.0, i: 10.0, d: 6.0}

joint_3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_3
  pid: {p: 20.0, i: 10.0, d: 6.0}